### ISSUE TITLE
Hello,What the default user name and userpassword？

### ISSUE THREAD

**Issue by Foundj** [robsecord/angular2-meteor-base#1]
What the default user name and userpassword？

**Comment by robsecord** [comment]
There isn’t one.  You will need to create the signup page (follow Meteor/Angular tutorial).

I connect it to another App running a mongo DB instance which has my user accounts.
- Rob

**Comment by Foundj** [comment]
OK,THX! This is Will update for a long time？blaze with ng2，Which one do you favor?

**Comment by robsecord** [comment]
I am not sure if it will be updated anytime soon.  Waiting for full release on angular 2.  It is just not ready yet.  So we went with Blaze for now.  See my other repo: blaze-meteor-base.

Sent from my Samsung device

-------- Original message --------

**Comment by Foundj** [comment]
thx for your great answer！good job！

**Comment by robsecord** [comment]
Thx, hope it works for you!  Feel free to fork it and submit changes!
